plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.github.CENTURYCLOUD'

task customJar(type: Jar) {
    archiveBaseName = 'device-libs-desktop'
    from zipTree(file("libs/ReaderAPI20250926.jar"))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'com.github.CENTURYCLOUD'
            artifactId = 'device-libs-desktop'
            
            artifact(customJar)
        }
    }
}
