plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.github.CENTURYCLOUD'

// Validación estricta: si viene vacía o solo con espacios, asigna '1.0.0'
def envVersion = project.hasProperty('version') ? project.property('version').toString().trim() : ''
version = (envVersion && envVersion != 'unspecified') ? envVersion : '1.0.0'

task customJar(type: Jar) {
    archiveBaseName = 'device-libs-desktop'
    from zipTree(file("libs/ReaderAPI20250926.jar"))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = group
            artifactId = 'device-libs-desktop'
            version = project.version
            
            artifact(customJar)
        }
    }
}
